---
name: spellcheck

on:
  push:
    tags-ignore:
    - '**'
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  build:
    name: spellcheck
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.23.x

    - name: Check out code into the Go module directory
      uses: actions/checkout@v4

    - name: Spellcheck
      run: |
        go install github.com/client9/misspell/cmd/misspell@latest
        find . -type f | xargs misspell -source=text -error
