---
name: Tests

on:
  push:
    tags-ignore:
    - '**'
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  build:
    name: Tests
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.20.x

    - name: Check out code into the Go module directory
      uses: actions/checkout@v3

    - name: Build
      run: go build ./...

    - name: Test
      run: |
        make test
